language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - 8.0
    - nightly

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
    - composer install

after_success:
    - composer global require infection/infection
    - ~/.config/composer/vendor/bin/infection
